### ISSUE TITLE
BCV error

### ISSUE THREAD

**Issue by coorproduccionpromaceca** [fcoagz/api-pydolarvenezuela#2]
la tasa del BCV no es la correcta, del resto muy buena api

**Comment by fcoagz** [comment]
Buenos días @coorproduccionpromaceca. La obtención de las tasas de BCV es a través desde su página `bcv.org.ve` como parámetro de la ruta `page` , realiza la solicitud de la siguiente manera: 

https://pydolarvenezuela-api.vercel.app/api/v1/dollar/page?page=bcv

**Comment by coorproduccionpromaceca** [comment]
agradecido por tu respuesta, yo lo estaba buscando por aqui [https://pydolarvenezuela-api.vercel.app/api/v1/dollar/](https://pydolarvenezuela-api.vercel.app/api/v1/dollar/) para obtener de una vez la tasa bcv y la de enparalelo

pero parece que es un tema de actualizacion, por ejemplo la de paralelo no se ha actualizado desde la 1am y ya cambio de precio

**Comment by fcoagz** [comment]
De hecho es la página informativa, tiene retraso en cuanto las actualizaciones de los monitores, es por eso que me he basado en que tú puedas elegir el proveedor para la obtención de los datos del dólar

**Comment by fcoagz** [comment]
En qué se encuentra es la ruta por defecto, sí quieres obtener las tasas en tiempo real, accede a su página argumento dolo en el parámetro `page`, de la ruta que te indique
