### ISSUE TITLE
Tasa del dolar y del euro con cuatro decimales

### ISSUE THREAD

**Issue by Larlobo17** [fcoagz/api-pydolarvenezuela#24]
Muy buenos días, antes de comenzar quiero agradecer por el valioso servicio que están prestando y que en realidad es de mucha utilidad. Desde hace mas de un mes estoy utilizando su API "https://pydolarve.org/api/v1/dollar?page=bcv" para cargar la tasa del dólar y del euro. Durante ese tiempo no presente ningún problema, pero a partir del día 30/09/2024 al consumir su API no me retorna la tasa con los 4 decimales.

Me gustaría saber si tienen pensado colocar de nuevo los cuatro decimales, o si tienen una API donde lo pueda consumir. Quedo atento a su respuesta.

Muchas gracias por su atención.

**Comment by fcoagz** [comment]
Buenos días, amigo. Muchas gracias. Debido a que diversas página no rellenaba la propiedad price_old. Se decidió presenciar el precio viejo del monitor. Además no hubo problema desde entonces ya pensé que la propiedad estaba en desuso. Que nadie lo iría a utiliza. 

Posiblemente está semana vuelva a incorporar una propiedad para obtener el precio largo del dólar.

**Comment by Larlobo17** [comment]
Para mi seria de mucha ayuda poder consumir la tasa con todos los decimales, de verdad muchas gracias por tu atención y por tu valioso tiempo.

**Comment by fcoagz** [comment]
@Larlobo17 Buenos días, amigo. Se aplicaron los cambios. Verifica la documentación

**Comment by fcoagz** [comment]
Empezara a generar los decimales a partir de la siguiente actualización que sea requerida de la pagina
