### ISSUE TITLE
BCV Error

### ISSUE THREAD

**Issue by tipoxd** [fcoagz/api-pydolarvenezuela#3]
actualmente cuando quiere solicitar el precio del BCV

![image](https://github.com/fcoagz/api-pydolarvenezuela/assets/19245713/81accc98-6f1e-4fe4-9a58-819fbf1d8c54)

muestra este error.

es el Unico detalle que le veo actualmente.

Excelenete api.

**Comment by fcoagz** [comment]
Buenas tardes @tipoxd, en su última actualización se redujeron las rutas de la API. Ahora, se manejará en una única ruta `GET /api/v1/<currency>`.

En cuanto a los parámetros que puedes usar en esta ruta, son los siguientes:

| Parámetros | Tipo   | Descripción                                                  |
|------------|--------|--------------------------------------------------------------|
| page       | string | Opcional. Indica el nombre de la página donde deseas obtener su valor. |
| monitor    | string | Opcional. Indica el monitor específico.                      |

**Comment by fcoagz** [comment]
Como sabemos, la ruta GET /api/v1/<currency> es donde currency representa la moneda en la que se expresarán los precios, que puede ser `dollar` o `euro`. Saludos
