### ISSUE TITLE
Error de request con Ivenezuela y Dpedidos

### ISSUE THREAD

**Issue by santiagohernandezs** [fcoagz/api-pydolarvenezuela#4]
Al añadir como parámetro la página ivenezuela y dpedidos arroja el siguiente error.

- Request a `/api/v1/dollar?page=ivenezuela`
```json
{
  "error": "An error occurred: __init__() takes 2 positional arguments but 3 were given"
}
```

- Request a `/api/v1/dollar?page=dpedidos`
```json
{
  "error": "An error occurred: HTTPSConnectionPool(host='api.lyldesarrollo.com', port=443): Max retries exceeded with url: /minmaxhistorial (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fafd98ee490>: Failed to resolve 'api.lyldesarrollo.com' ([Errno -2] Name or service not known)\"))"
}
```

**Comment by fcoagz** [comment]
Muchas gracias por el reporte amigo! La página de dpedidos dejó de existir hace algún tiempo. Aunque aún no he tenido la oportunidad de eliminarla, espera una actualización en las próximas horas.
