### ISSUE TITLE
Actualizar Readme para detallar ruta /unit/

### ISSUE THREAD

**Issue by orozCoding** [fcoagz/api-pydolarvenezuela#8]
Hola amigo.

Primero que nada, genial el API que armaste. Te felicito.

Creo que podrías actualizar el Readme para explicar un poco mejor la intención de uso de la ruta

````
https://pydolarvenezuela-api.vercel.app/api/v1/<currency>/unit/<page>
````

Haciendo algunos test, esa es la ruta que más aprovecharía yo de esta API, y me llama la atención que no está explicitamente explicada en los `Endpoints`.

**Comment by fcoagz** [comment]
Buenas noches bro. Muchas gracias! Tenia pensado eliminarla en el futuro. Debido a que esta ruta:

```
https://pydolarvenezuela-api.vercel.app/api/v1/dollar
```

argumenta por defecto el parámetro `page`, por lo que puedes especificar simplemente el parámetro `monitor` como lo estuvieses haciendo `https://pydolarvenezuela-api.vercel.app/api/v1/<currency>/unit/<page>` (toma la misma página).

```
https://pydolarvenezuela-api.vercel.app/api/v1/dollar?monitor=bcv
```

---

La primera versión de la API tenía esos dos endpoints. A medida que iba aprendiendo nuevas cosas de Flask, iba puliendo el código y simplificándolo. Aun tengo cosas por mejorar en la librería, me he tomado estos días estudiando. 

En cuanto pueda tener avances de los cambios que tendrá la API, lo alistare [Endpoints](https://github.com/fcoagz/api-pydolarvenezuela?tab=readme-ov-file#endpoints).

**Comment by orozCoding** [comment]
Tiene sentido. De igual forma creo que estaba chévere esa ruta. Un pelo más limpia, y revisando el código, se entiende que intenta buscar el monitor entre todas las páginas.

De igual forma, no hace gran diferencia, y de cualquier manera hace un buen trabajo la API.

Recomendaría buscar siempre la consistencia. Por ejemplo, `enparalelovzla` no está listado como un monitor como tal en el Readme.

De entrada (sin ver el código) pensaría que en este query:
````
https://pydolarvenezuela-api.vercel.app/api/v1/dollar?monitor=enparalelovzla
````

buscaría info de todas las páginas y trataría de encontrar un monitor con ese nombre.

E.g. página alcambio > monito enparalelovzla

Pero intentando con

````
https://pydolarvenezuela-api.vercel.app/api/v1/dollar?monitor=activo
````
No pasa lo mismo (e.g. no encuentra en la página bcv el monitor "activo")


Por lo que, si uso el API y me interesan solo los dos precios "bcv" vs "enparalelo", yo buscaría hacer:

````
curl -X GET "https://pydolarvenezuela-api.vercel.app/api/v1/dollar?page=bcv&monitor=activo"
curl -X GET "https://pydolarvenezuela-api.vercel.app/api/v1/dollar?page=alcambio&monitor=enparalelovzla"
````

Esto para intentar ser consistente y jugarla más seguro.

En cualquier caso los resultados están geniales. Solo es aclarar un poco más el Readme, que nunca está de más.

Mucho éxito!

**Comment by fcoagz** [comment]
Respecto a lo que dijiste, no. Seria interesante aunque claro, para realizar la búsqueda de todos los datos estaríamos también validando que dato a mostrar, de por si la mayoría de los monitores tienen el mismo `key` en diversas paginas. No seria viable debido a que cada pagina tiene rumbos diferente (Actualización de los datos), y para que la API este eligiendo aleatoriamente el dato a mostrar, también el tiempo en que realizaría la búsqueda....

Y hablando de listar algún monitor en el Readme. Los que se encuentran es para dar ejemplo, mas no especifico que monitores tiene cada quien, al paso del tiempo van agregando nuevos bancos, u otro monitor. Cada usuario conoce donde esta obteniendo los resultados.

Entiendo con lo que dices con la documentación de la API, lo tendré en cuenta.

**Comment by orozCoding** [comment]
Tiene sentido amigo. 👍🏻
